apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: financial-portfolio
  labels:
    app: grafana

data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        isDefault: true
        editable: true
