apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
  namespace: financial-portfolio

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090']
      - job_name: 'flask-app'
        static_configs:
          - targets: ['flask:5050']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
