services:
  postgres:
    image: postgres:15
    container_name: investment_postgres
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_DB: investment_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: thisisastrongpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - portfolio_files:/uploads
      - ./init-file/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: |
      bash -c "
      mkdir -p /uploads
      chmod -R 755 /uploads
      chmod +x /docker-entrypoint-initdb.d/init-db.sh
      docker-entrypoint.sh postgres
      "
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d investment_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  flask-app:
    build:
      context: ../app/Backend
      dockerfile: flask-dockerfile
    image: portfolio/investment-flask:latest
    container_name: investment_flask
    restart: always
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: investment_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: thisisastrongpassword
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY:-your-api-key-here}
    ports:
      - "5050:5050"
    volumes:
      - portfolio_files:/uploads
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    command: python main.py

  prometheus:
    build:
      context: ../monitoring
    image: local/prometheus-with-config
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - flask-app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  frontend:
    build:
      context: ../app/Frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5050}
    image: portfolio/frontend:latest
    container_name: frontend
    restart: always
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5050}
      - NODE_ENV=production
    ports:
      - "3001:3001"
    depends_on:
      - flask-app

volumes:
  pgdata:
    driver: local
  portfolio_files:
    driver: local

networks:
  default:
    name: investment_network
