services:
  postgres:
    image: postgres:15
    container_name: investment_postgres
    restart: always
    environment:
      POSTGRES_DB: investment_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: thisisastrongpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - portfolio_files:/var/lib/postgresql/portfolio_files
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    command: |
      bash -c "
      # Create the portfolio_files directory before postgres starts
      mkdir -p /var/lib/postgresql/portfolio_files
      chmod -R 700 /var/lib/postgresql/portfolio_files
      # Make init script executable inside container
      chmod +x /docker-entrypoint-initdb.d/init-db.sh
      # Start postgres normally
      docker-entrypoint.sh postgres
      "

volumes:
  pgdata:
  portfolio_files: