version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: investment_postgres
    restart: always
    environment:
      POSTGRES_DB: investment_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: thisisastrongpassword
    ports:
      - "5001:5001"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
