apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-k8s
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  
  resources:
    requests:
      storage: 10Gi
