apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-k8s
  labels:
    app: postgres
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/tmp/data/postgres"
    type: DirectoryOrCreate
