apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres  
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=                # base64 for "admin"
  POSTGRES_PASSWORD: dGhpc2lzYXN0cm9uZ3Bhc3N3b3Jk  # base64 for "thisisastrongpassword"
